name: MichaelLaverty
favicon: null
layout_spectrum: 0.4020789638161659
typography_spectrum: 0.28473382466472685
title: 'Michael Laverty :: Mlav#7 :: British Superbike Rider For Tyco BMW'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9651962348725647
  lightness: 0.08217869303189218
  saturation: 0.7355665732175112
  rhythmicContrast: 0.005545392632484436
purpose: []
